# Generated by Django 3.1.7 on 2021-04-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopNotifyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, null=True)),
                ('from_email', models.EmailField(default='info@photobank.com', max_length=254)),
                ('message', models.TextField(max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Сообщение топ юзерам',
                'verbose_name_plural': 'Сообщения топ юзерам',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file_name', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
